### ISSUE TITLE
Scudcloud remains empty when initially offline

### ISSUE THREAD

**Issue by oliverbienert** [raelgc/scudcloud#158]
Hi,

I frequently choose to manually establish an internet connection after I booted my system. However, when scudcloud is started offline (I have it in a xfce session, so it would start automatically), it shows nothing (which is ok), but after going online scudcloud keeps being empty. Reloading has no effect whatsoever. I have to quit and restart the application.

**Comment by moonwolf-github** [comment]
Same issue here (Fedora with KDE).

**Comment by raelgc** [comment]
Hi @oliverbienert and @moonwolf-github, thank you for reporting this issue.

I'll try address it in the next weeks.

Reminder to myself (or anyone with code skills): check `QWebPage::loadFinished(false)` as described [here](http://stackoverflow.com/questions/7279046/how-to-get-detailed-error-message-when-qtwebkit-fails-to-load-a-page).

**Comment by raelgc** [comment]
I'm adding a "loading" message in the status bar.

**Comment by raelgc** [comment]
Fixed in `v1.0.63`

**Comment by moonwolf-github** [comment]
Just want to say this is the best improvement for scudcloud! (:)

**Comment by danieliser** [comment]
I am still getting this in the latest version from PPA. If I am not connected before opening the screen will never load, even after trying refresh/reload. I have to Quit and reopen for it to start loading.

**Comment by edmundcraske** [comment]
I still see this sometimes too...

**Comment by raelgc** [comment]
To make clear: we didn't tackle this issue. If you starts ScudCloud offline, it'll no try reconnect later. We just add a simple status bar at the bottom to make clear when ScudCloud is loading Slack or not.
