### ISSUE TITLE
Notification on Xubuntu

### ISSUE THREAD

**Issue by Jesse-Millwood** [raelgc/scudcloud#193]
The body of the notification in Xubuntu 14.04 contains source for functions. Here is a screen shot:
![selection_063](https://cloud.githubusercontent.com/assets/5342237/9076308/e262ec9a-3aee-11e5-9fce-d5e1297e2514.png)

It was installed with apt-get and the ppa.

**Comment by tricksunga** [comment]
Also on Elementary OS Freya.

![screenshot from 2015-08-05 10 48 53](https://cloud.githubusercontent.com/assets/12521432/9077352/a8c17c38-3b5f-11e5-892d-cc03503c6a52.png)

Latest version installed via PPA.

**Comment by 0xd3adsh3ll** [comment]
Also on linuxmint.
![_001](https://cloud.githubusercontent.com/assets/4302413/9079891/6a7a9a7a-3b57-11e5-9931-297acff25ed5.jpg)

**Comment by sozonnyk** [comment]
Same on Kubuntu 15.04
![2015-08-05 16_50_31-kubuntu](https://cloud.githubusercontent.com/assets/1960621/9079916/472747ea-3b92-11e5-9b2c-655b05319e1b.png)

**Comment by weirdobeaver** [comment]
Ubuntu 14.10 I have the same problem

**Comment by Slater91** [comment]
Issue confirmed on Linux Mint 17.2 with Scudcloud .53 (latest version).

**Comment by svogler-trv** [comment]
Same here on Ubuntu 14.04 since the latest update to scudcloud 1.0-53
![pasted_image_at_2015_08_05_09_58](https://cloud.githubusercontent.com/assets/11662099/9081102/ce17d1e0-3b59-11e5-9b1d-3a239df2e044.png)

**Comment by mbootsman** [comment]
Same problem here. Ubuntu 15.04

**Comment by tuxinaut** [comment]
Me too. `Ubuntu 14.04`

**Comment by royzer** [comment]
+1. Ubuntu 14.04 32 bit.

**Comment by nazar-pc** [comment]
Yes, everyone gets this.
Looks like somewhere there is `func` instead of `func()`, though, I didn't found anything like this in last few commits, maybe something changed on Slack's side?

**Comment by juuh42dias** [comment]
+1.Ubuntu 14.04 64Bit

**Comment by ricsipontaz** [comment]
Me too. Ubuntu 14.04 64bit.

**Comment by raelgc** [comment]
This was a change in Slack side. I just noted in my desktop too and updated code to match the new changes.

Ubuntu PPAs will be updated in few minutes.

**Comment by mbootsman** [comment]
Cool! Thanks for the fast fix @raelgc

**Comment by ricsipontaz** [comment]
@raelgc Thanks, It works well. :+1:

**Comment by sagotsky** [comment]
The fix worked on debian stable.  TY.  I couldn't get the ubuntu ppa to work though, although the .deb package in there worked when I downloaded it.

**Comment by raelgc** [comment]
Reminder to myself: I fixed this issue before read it here in GitHub, so the commit (76f9e78) gone to master branch directly.

**Comment by nahojkap** [comment]
I just installed the client and the issue still occurs.  Seems the PPA is providing 1.0.50_all still?  Is there another step needed in order to get updates?

**Comment by raelgc** [comment]
@johanlindquist Latest version is 1.0.54. If you're using `apt`, please run a `sudo apt-get update` before install it.

**Comment by nahojkap** [comment]
Ah, seems it is not available for 14.10 (Utopic)?

**Comment by raelgc** [comment]
@johanlindquist Unfortunatelly, Canonical Launchpad do not allow me to provide the .deb for Utopic as it's no more supported. But you can manually download the `.deb` file to other versions and install.

**Comment by nahojkap** [comment]
@raelgc thanks, that did the trick!
