### ISSUE TITLE
The team icon does not display if the team name has a "'" (single quote)

### ISSUE THREAD

**Issue by smaboshe** [raelgc/scudcloud#264]
Hello!

Loving Scudcloud!

Just a quick note that when a Team name has a `'` in it, the icon on the left stripe will not show.

For example for a list of Teams:
1. FIFA 15 Superstars
2. Charlotte's Web
3. Peanut Butter Bandits

I'll be able to sign in to all the teams and switch between them but the icon for Team number 2, "Charlotte's Web", will not show.

If I change it to "Charlottes Web", the Team icon displays as expected.

**Comment by raelgc** [comment]
Hi @smaboshe, thank you for reporting this issue!

I've published a new version with a fix. If it not works, please, re-open this issue :)

**Comment by smaboshe** [comment]
It works!

**Comment by Rudloff** [comment]
I still don't see one of my teams that has a single quote in its name.

**Comment by raelgc** [comment]
Hi @Rudloff. Which ScudCloud version are you running?

**Comment by Rudloff** [comment]
I have the 1.1-2 package Ubuntu package.

**Comment by raelgc** [comment]
You're right, I've changed my test team and the icon is not loaded. Let me fix it.

**Comment by raelgc** [comment]
@Rudloff I just published new Ubuntu versions with the fix. Please upgrade!

**Comment by Rudloff** [comment]
It works, thanks !

**Comment by raelgc** [comment]
Yw! Thank you for reporting this and sorry for the inconvenience!
