### ISSUE TITLE
entire application canvas goes blank

### ISSUE THREAD

**Issue by dhgwilliam** [raelgc/scudcloud#364]
I haven't been able to repro, but it's happened several times to me today. i can't destroy the window with my WM and i need to, e.g. `pkill -f scudcloud`

output of `facter` https://gist.github.com/dhgwilliam/1e15ba0a7ac467aa83c1

**Comment by raelgc** [comment]
Hi @dhgwilliam,

Which is your WM?

**Comment by dhgwilliam** [comment]
I'm using i3wm

i3 version 4.10.3 (2015-07-30, branch "4.10.3") © 2009-2014 Michael Stapelberg and contributors

**Comment by raelgc** [comment]
Right @dhgwilliam, thanks for the feedback.

Can you start ScudCloud from the command line and paste the output when this happens?

**Comment by dhgwilliam** [comment]
I've tried that and it doesn't seem to print any messages when it hangs...
I'll try again this afternoon.

**Comment by raelgc** [comment]
Right.

Maybe you can see if the black canvas stops to happen if starting ScudCloud with `QT_GRAPHICSSYSTEM=native scudcloud`

**Comment by dhgwilliam** [comment]
I tried running with QT_GRAPHICSSYSTEM=native today and it didn't stop the
issue. Also, there's no output in the CLI at all. In this case, I'm pretty
sure I clicked on a link and when I came back to the app it was blank.

```
 ~/github/browser-laptop   master  QT_GRAPHICSSYSTEM=native scudcloud
SpellCheck: Language = "en_US"

Created new window in existing browser session.
Created new window in existing browser session.


^C%
```

**Comment by raelgc** [comment]
Any lucky if you try this way?

```
nohup scudcloud >/dev/null 2>&1 &
```

**Comment by raelgc** [comment]
@dhgwilliam Please? :)

**Comment by dhgwilliam** [comment]
@raelgc I haven't run in to the issue lately. It's possible it was fixed in one of the recent releases? If I don't run in to it in the next 24 hours or so, I'll close the ticket.

**Comment by raelgc** [comment]
Thanks @dhgwilliam. Feel free to open this issue in case this start to happen again!

**Comment by Rawa** [comment]
@dhgwilliam This issue is still present for me, using i3wm. However, I doubt this issue is isolated to i3wm. When starting scudcloud w/o any internet connection, the screen will eventually go blank after failing to load slack. After failed to retrieve slack the client will not fetch the start page when doing a refresh (F5).

Here is an example of how the program looks:
http://upload.davidgoransson.com/scudcloud_black.png
After a while the bottom row, containing "Loading Slack...", will disappear.

**Comment by raelgc** [comment]
Hi @Rawa, thanks for the additional info.

Indeed, there is no code handling a connection timeout for now.
