### ISSUE TITLE
Voice call support

### ISSUE THREAD

**Issue by kofalt** [raelgc/scudcloud#412]
Slack has added a new [voice call](https://get.slack.help/hc/en-us/articles/216771908) feature, and it's pretty slick.
When I hit the new call button in Scudcloud, nothing happens. 

When running Slack in Chrome, a new `slack.com/call/id` tab is opened to start the call.
My guess is that Scudcloud just needs to support opening a browser window from this button.

Version info:

```
$ cat /etc/lsb-release

DISTRIB_ID=LinuxMint
DISTRIB_RELEASE=17.1
DISTRIB_CODENAME=rebecca
DISTRIB_DESCRIPTION="Linux Mint 17.1 Rebecca"

$ scudcloud --version

ScudCloud 1.18
Python 3.4.3
Qt 4.8.6
PyQt 4.10.4
SIP 4.15.5
```

**Comment by raelgc** [comment]
Hi @kofalt and thanks for reporting this!

Sounds like a nice workaround!

I'll work on this tomorrow at my morning and publish a new version.

**Comment by kofalt** [comment]
:raised_hands:

**Comment by raelgc** [comment]
Playing a bit with the voice call: the trailing `id` to start a new call is the current channel id.

**Comment by raelgc** [comment]
@kofalt What happens when someone tries to call you?

**Comment by kofalt** [comment]
I saw a momentary link to the call, and then it would immediately switch to a missed call notification.

![missed](https://cloud.githubusercontent.com/assets/265071/13621052/19a62670-e55a-11e5-89b9-3a867e051acc.png)

**Comment by raelgc** [comment]
Re-opening, as this is fixed only to start calls.

**Comment by raelgc** [comment]
Slack changed the button id. I'll update to reflect it.

**Comment by mattias-avelin** [comment]
Any ETA on this feature? Would be really awesome to have it!

**Comment by raelgc** [comment]
@mattias-avelin I just fixed the button to start the call. To fix receive a call, I need to check what is expected to be in place.

Last time I tried, the work colleagues tried to call me, but the official client was not working with the calls too. I need to try again.

**Comment by TheCrimsonIdol** [comment]
This issue is still present. Totally not possible to make or receive calls from Slack Linux app.

```
Distributor ID:	LinuxMint
Description:	Linux Mint 18.1 Serena
Release:	18.1
Codename:	serena
```
