### ISSUE TITLE
Desktop notifications disabled + multi-team chat

### ISSUE THREAD

**Issue by Slater91** [raelgc/scudcloud#67]
Hi there! Thanks for this awesome work.

I am encountering apparently random issues with ScudCloud. They seem to be correlated so I will write about them together. I use Slack to communicate with two different teams and I use ScudCloud to communicate with both under Linux. At random times the software seems to "forget" I logged in to two teams and only shows one, saying that desktop notifications are disabled - but then there is no way to re-enable them.
Another symptom is the lack of clickable elements on the menu - so I cannot actually click on "preferences" nor login to another team.

This is happening randomly with no apparent reason - I start ScudCloud and it's messed up.

I use Linux Mint 17.1 Cinnamon 64-bit.

**Comment by raelgc** [comment]
Hi @Slater91, thank you for reporting this issue!

I think all the issues are related to notify-osd stopping works and getting restarted often.

I tried to restart the `libnotify2` in this cases, but the issue appears to be more deep, thrown from python dbus libraries.

You can double check this starting ScudCloud by the command line, and then check it when the notifications stopped to work. Probably you'll see the stack trace related to notifications.

For now, the only workaround is to restart ScudCloud in this situation.

**Comment by Slater91** [comment]
Hi @raelgc, thanks for your quick and kind reply.
Alas the problem is not fixed with a restart: the only way to solve it is to delete the ~/.scudcloud configuration file and start from scratch with configuration - it is fixed until the next time the bug is triggered.
I tried restarting ScudCloud from terminal a few times but nothing happened; I will keep you posted about any news I shall find.

**Comment by raelgc** [comment]
@Slater91 oh, sad that even a restart cannot fix it :(

Hope you can find a consistent way to reproduce it.

To check if the notify-osd is the problem, kill the notify-osd process. Then check if ScudCloud start to behave weirdly.

**Comment by Slater91** [comment]
Hi @raelgc,
I have not found a way to reproduce it, but after a few days without a problem I got this message a few minutes ago starting ScudCloud from the terminal: `"sni-qt/3400" WARN  09:25:15.562 void StatusNotifierItemFactory::connectToSnw() Invalid interface to SNW_SERVICE`
Is this a problem related to `libnotify2` in the end?

Edit: by the way, I tried to restart it from the terminal and it displayed the message again, but this time everything is working, so I cannot relate the message to the issue. Is there something deeper inside the program or the libraries?

**Comment by raelgc** [comment]
Fixed in #93. Please, update and let me know if it works now :)

**Comment by Slater91** [comment]
Hi @raelgc, I actually ran in the same "notifications not working" message a couple days ago (updated to latest version available then, 1.0-30 I guess) but found out I only needed to select another channel or private conversation to make the message disappear. It otherwise works perfectly.
Thank you so much for your work!

**Comment by Slater91** [comment]
Just a quick update: I confirm it still happens (version 1.0-31 installed), though it does affect functionality.

**Comment by jprupp** [comment]
I am getting this problem too. I am using Ubuntu 15.04. Sometimes I open the application, and it shows me one team and a warning stating that there are no notifications. I can recover either restarting the application, or attempting to sign into the other team, at which point I just select the other team from the list of already signed-in teams. The team bar appears, and the notification problems go away.

**Comment by raelgc** [comment]
This was fixed in the latest update, as a fix for #163 

Please, if you're not still on this version, update to `1.0.56`.

**Comment by jprupp** [comment]
Yesterday at 19:07 I upgraded to version 1.0.56. For some reason the problem was presenting itself today in the morning, but after I deleted an account that was having notification issues and added it again, the problem seems to have been solved. I cannot reproduce it anymore. Thank you!
